### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by whaleygeek** [whaleygeek/punchcard_reader#2]
It isn't

**Comment by whaleygeek** [comment]
Need to pull over the portscan and pyserial module from https://github.com/whaleygeek/bitio and then this will be Python 3 compatible.

**Comment by whaleygeek** [comment]
Wait for the bitio portscan module to be changed in bitio to change the name of the portscan.cache to that of the device name first, then that will also allow bitio and punchcard_reader to run concurrently in the same Python program.

**Comment by whaleygeek** [comment]
Had a quick look at this. Remember that Python3 imports work differently. I did a quick test...

delete portscan.py
copy portscan folder and serial folder from bitio project into this folder
run it up with python3

```Traceback (most recent call last):
  File "card2csv.py", line 17, in <module>
    import cardreader
  File "/Users/davidw/tmp/punchcard_reader/cardreader/__init__.py", line 5, in <module>
    from arduino import *
ModuleNotFoundError: No module named 'arduino'
```

I suspect this is because of the differences in how package imports work between Python2 and Python3, probably *all* the package based imports need re-coding as well, so this is not a quick fix, and needs to be done and tested properly.

cc @GemmaMayLatham

**Comment by whaleygeek** [comment]
Gemma reported that this quick fix worked for her, must be a python version/platform thing I guess. Will have to do this properly later and re test it.
